osx_image: xcode7
sudo: false
language: objective-c

env:
  matrix:
      - DESTINATION="OS=9.0,name=iPad 2"
      - DESTINATION="OS=9.0,name=iPad Air"
      - DESTINATION="OS=9.0,name=iPhone 5"
      - DESTINATION="OS=9.0,name=iPhone 6s"

before_install:
    - cd Example

script:
    - set -o pipefail
    - git submodule update --init --recursive
    - xcodebuild -version
    - xcodebuild -workspace DTTableViewManager.xcworkspace -scheme DTTableViewManager -configuration Debug -sdk iphonesimulator -destination "$DESTINATION" test -enableCodeCoverage YES | xcpretty -tc

after_success:
    - bash <(curl -s https://codecov.io/bash) 
